name: 'Tencent Serverless Action'
description: Github action for serverless framework
runs:
  using: 'composite'
  steps:
    - run: npm install -g serverless
      shell: bash
    - run: sls deploy --debug
      shell: bash          
branding:
  icon: 'upload-cloud' 
  color: blue
